// Field of view — Bresenham raycasting.
//
// The Rust version uses recursive shadowcasting with f64 slopes. That's
// impossible on a 1 MHz 8-bit CPU with a 256-byte hardware stack.
//
// Instead we cast ~38 rays from the player to the perimeter of a circle
// (radius 6), using Bresenham's line algorithm (integer-only). Each ray
// marks tiles visible until it hits a wall.
//
// Cost: ~38 rays × ~4 tiles/ray × ~50 cycles/tile ≈ 7,600 cycles ≈ 7.5 ms.
// Well under one frame (16.7 ms at 60 Hz NTSC).

use crate::map;

pub const FOV_RADIUS: u8 = 6;

const MAP_SIZE: usize = map::MAP_SIZE;

static mut VISIBLE: [u8; (MAP_SIZE + 7) / 8] = [0; (MAP_SIZE + 7) / 8];
static mut EXPLORED: [u8; (MAP_SIZE + 7) / 8] = [0; (MAP_SIZE + 7) / 8];

// --- Bitfield operations ---

#[inline(always)]
fn bit_idx(x: u8, y: u8) -> (usize, u8) {
    let i = (y as usize) * (map::MAP_W as usize) + (x as usize);
    (i / 8, 1u8 << (i % 8))
}

#[inline(always)]
pub fn is_visible(x: u8, y: u8) -> bool {
    if !map::in_bounds(x, y) { return false; }
    let (byte, bit) = bit_idx(x, y);
    unsafe { VISIBLE[byte] & bit != 0 }
}

#[inline(always)]
pub fn is_explored(x: u8, y: u8) -> bool {
    if !map::in_bounds(x, y) { return false; }
    let (byte, bit) = bit_idx(x, y);
    unsafe { EXPLORED[byte] & bit != 0 }
}

#[inline(always)]
fn mark_visible(x: u8, y: u8) {
    let (byte, bit) = bit_idx(x, y);
    unsafe {
        VISIBLE[byte] |= bit;
        EXPLORED[byte] |= bit; // visible implies explored
    }
}

fn clear_visible() {
    unsafe {
        for b in VISIBLE.iter_mut() { *b = 0; }
    }
}

/// Count explored floor tiles.
pub fn explored_floor_count() -> u16 {
    let mut count: u16 = 0;
    for y in 0..map::MAP_H {
        for x in 0..map::MAP_W {
            if is_explored(x, y) && map::tile_at(x, y) == map::TILE_FLOOR {
                count += 1;
            }
        }
    }
    count
}

// --- Bresenham ray casting ---

/// Cast a single ray from (ox, oy) toward (tx, ty), marking tiles visible.
/// Stops when hitting a wall (marking the wall itself as visible) or leaving bounds.
fn cast_ray(ox: u8, oy: u8, tx: u8, ty: u8) {
    let mut x = ox as i8;
    let mut y = oy as i8;
    let target_x = tx as i8;
    let target_y = ty as i8;

    let dx = if target_x > x { target_x - x } else { x - target_x };
    let dy = if target_y > y { target_y - y } else { y - target_y };
    let sx: i8 = if target_x > x { 1 } else { -1 };
    let sy: i8 = if target_y > y { 1 } else { -1 };
    let mut err = dx - dy;

    loop {
        let ux = x as u8;
        let uy = y as u8;

        if !map::in_bounds(ux, uy) { break; }

        mark_visible(ux, uy);

        // Stop after marking a wall visible (wall blocks further sight)
        if map::tile_at(ux, uy) == map::TILE_WALL { break; }

        // Reached target — done
        if x == target_x && y == target_y { break; }

        let e2 = err * 2;
        if e2 > -dy {
            err -= dy;
            x += sx;
        }
        if e2 < dx {
            err += dx;
            y += sy;
        }
    }
}

/// Precomputed perimeter offsets for FOV_RADIUS=6.
/// These are the (dx, dy) offsets from the origin to each tile on the
/// circle perimeter, generated by stepping around the Bresenham circle.
/// Approximately 38 points.
const PERIMETER: [(i8, i8); 40] = [
    // Top row, left to right
    (-6, 0), (-6, -1), (-5, -2), (-5, -3), (-4, -4), (-3, -5), (-2, -5), (-1, -6), (0, -6),
    (1, -6), (2, -5), (3, -5), (4, -4), (5, -3), (5, -2), (6, -1), (6, 0),
    // Bottom half
    (6, 1), (5, 2), (5, 3), (4, 4), (3, 5), (2, 5), (1, 6), (0, 6),
    (-1, 6), (-2, 5), (-3, 5), (-4, 4), (-5, 3), (-5, 2), (-6, 1),
    // Fill corners for coverage
    (-4, -5), (4, -5), (4, 5), (-4, 5),
    (-3, -6), (3, -6), (3, 6), (-3, 6),
];

/// Compute field of view from (ox, oy). Clears previous visible set,
/// casts rays to perimeter, marks all visible tiles including walls.
pub fn compute_fov(ox: u8, oy: u8) {
    clear_visible();

    // Origin is always visible
    mark_visible(ox, oy);

    // Cast a ray to each perimeter point
    for &(dx, dy) in PERIMETER.iter() {
        let tx = (ox as i8 + dx) as u8;
        let ty = (oy as i8 + dy) as u8;
        // Skip if target is wildly out of bounds (unsigned wraparound)
        if tx >= map::MAP_W || ty >= map::MAP_H { continue; }
        cast_ray(ox, oy, tx, ty);
    }
}

/// Check line-of-sight between two points (for monster awareness).
/// Casts a single Bresenham ray — does NOT modify the visible/explored sets.
pub fn can_see(ox: u8, oy: u8, tx: u8, ty: u8, radius: u8) -> bool {
    // Quick distance check (Chebyshev distance)
    let dx = if tx > ox { tx - ox } else { ox - tx };
    let dy = if ty > oy { ty - oy } else { oy - ty };
    let dist = if dx > dy { dx } else { dy };
    if dist > radius { return false; }

    // Walk a Bresenham line, checking for wall obstruction
    let mut x = ox as i8;
    let mut y = oy as i8;
    let target_x = tx as i8;
    let target_y = ty as i8;

    let ddx = if target_x > x { target_x - x } else { x - target_x };
    let ddy = if target_y > y { target_y - y } else { y - target_y };
    let sx: i8 = if target_x > x { 1 } else { -1 };
    let sy: i8 = if target_y > y { 1 } else { -1 };
    let mut err = ddx - ddy;

    loop {
        if x == target_x && y == target_y { return true; }

        let e2 = err * 2;
        if e2 > -ddy {
            err -= ddy;
            x += sx;
        }
        if e2 < ddx {
            err += ddx;
            y += sy;
        }

        let ux = x as u8;
        let uy = y as u8;
        if !map::in_bounds(ux, uy) { return false; }
        // Wall blocks LOS (but if the wall IS the target, we can see it)
        if map::tile_at(ux, uy) == map::TILE_WALL {
            return x == target_x && y == target_y;
        }
    }
}
